---
driver_plugin: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.8.5

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
      box_url: https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04
      box_version: 2.3.1
  - name: centos-7.3
    driver:
      box: bento/centos-7.3
      box_url: https://atlas.hashicorp.com/bento/boxes/centos-7.3
      box_version: 2.3.2

suites:
- name: default
  run_list: ["recipe[virtualbox]"]
  attributes: {}
